#include <SDL2/SDL.h>
#include "../c-vector/vec.h"
#include "bnl.h"

static Token_type get_tok_type(char c) {
    switch (c) {
    case '(':  return TOK_LPAR;
    case ')':  return TOK_RPAR;
    case ' ':
    case '\n':
    case '\t':
    case '\0': return TOK_NULL;
    default:   return TOK_SYM;
    }
}

static Token_vec lex_bnl(const char *bnl) {
  Token_vec tokens = vector_create();

  Token *t = vector_add_asg(&tokens);
  t->type = TOK_NULL;
  t->start = 0;
  t->length = 0;

  int i=0;
  do {
    Token_type nexttype = get_tok_type(bnl[i]);
    if (nexttype != t->type) {
      if (t->type != TOK_NULL) {
        t->length = i - t->start;
        t = vector_add_asg(&tokens);
      }
      t->type = nexttype;
      t->start = i;
    }
    ++i;
  } while (bnl[i-1]); // do/while + i-1 here to process final \0
  vector_pop(tokens);   // remove final TOK_NULL token generated by the \0

  return tokens;
}

AST AST_parse(char *bnl) {
  return (AST){
    .body = bnl,
    .tokens = lex_bnl(bnl),
  };
}

void AST_print(AST ast) {
  int length = vector_size(ast.tokens);
  for (int i=0; i<length; ++i) {
    Token t = ast.tokens[i];
    printf("%4d %2d %.*s\n",
           t.start, t.length,
           t.length, t.start + ast.body);
  }
}

void AST_compact(AST *ast) {
  int dest = 0;
  int numTokens = vector_size(ast);
  for (int i=0; i<numTokens; ++i) {
    Token *token = &ast->tokens[i];
    char *start = ast->body + token->start;
    char *end = start + token->length;
    for (; start<end; ++start) {
//      ast->body[dest] =
    }
  }
}
